version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: demo-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/exampledb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - /c/Users/harsh/Downloads/Project/postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Set your admin email
      PGADMIN_DEFAULT_PASSWORD: admin           # Set your admin password
    ports:
      - "5050:80"
